lion-back/.gitignore

venv settings

---

lion-back/BackEnd/accounts/urls.py
lion-back/BackEnd/accounts/views.py

accounts-수정

---

lion-back/BackEnd/accounts/urls.py
lion-back/BackEnd/accounts/views.py

token을 이용한 verification을 진행하기 위해 user/views.py를 수정하였습니다

[BE] user token verification 구현

---

lion-back/BackEnd/accounts/views.py
lion-front/src/api/confirmEmail.js
lion-front/src/app/App.js
lion-front/src/pages/signup.js

email auth ing

---

lion-back/BackEnd/BackEnd/urls.py
lion-back/BackEnd/diary/models.py
lion-back/BackEnd/diary/sentiment_analysis.py
lion-back/BackEnd/diary/views.py

감정분석 결과 저장 방식과 반환 방식을 변경하였습니다.

[BE] update sentiment-analysis return

---

lion-back/BackEnd/BackEnd/settings.py
lion-back/BackEnd/BackEnd/urls.py
lion-back/BackEnd/match/admin.py
lion-back/BackEnd/match/apps.py
lion-back/BackEnd/match/models.py
lion-back/BackEnd/match/serializers.py
lion-back/BackEnd/match/tests.py
lion-back/BackEnd/match/urls.py
lion-back/BackEnd/match/views.py

match app setting

---

lion-back/BackEnd/accounts/models.py

user 모델의 id를 기본 숫자가 아닌 조금 더 복잡한 형태의 개인 고유 id를 갖도록 수정하였습니다.

[BE] update user id format

---

lion-back/BackEnd/BackEnd/settings.py
lion-back/BackEnd/BackEnd/urls.py
lion-back/BackEnd/accounts/models.py

account 생성 시 사용자의 입력값이 반영되지 않는 현상을 해결하였습니다

[BE] account register update

---

lion-back/BackEnd/match/urls.py
lion-back/BackEnd/match/views.py

get matched_adviser info

---

lion-front/src/api/axiosConfig.js
lion-front/src/app/App.js
lion-front/src/components/MyPage/MyPage.js
lion-front/src/components/diary/DiaryModal.js
lion-front/src/components/diary/Posts.js
lion-front/src/components/features/Features.js
lion-front/src/components/features/Tab.js
lion-front/src/components/matching/ReceiveCounselor.js
lion-front/src/utils/auth.js

공유일기 부분 모달 라우팅으로 바꾸는 것과 공감기능 네가지 디자인. 피드백 아무나 해주면 진짜 감사ㅏ!

FE publicDiary design

---

lion-back/BackEnd/accounts/views.py
lion-front/src/api/auth.js

related to token

---

lion-back/BackEnd/accounts/urls.py
lion-back/BackEnd/accounts/views.py
lion-front/src/api/auth.js

get User Info

---

lion-front/src/api/auth.js
lion-front/src/api/privateDiary.js
lion-front/src/app/App.js
lion-front/src/components/MyPage/MyPage.js
lion-front/src/components/MyPage/PrivateDiary/DiaryDetail.js
lion-front/src/components/MyPage/PrivateDiary/PrivateDiary.js
lion-front/src/components/MyPage/PrivateDiary/WritePrivateDiary.js
lion-front/src/components/diary/Posts.js
lion-front/src/components/diary/PublicDiary.js
lion-front/src/components/diary/WritePublicDiary.js
lion-front/src/components/features/Features.js
lion-front/src/components/features/Tab.js
lion-front/src/components/matching/CategorySideBar.js
lion-front/src/components/matching/Matching.js
lion-front/src/components/matching/ReceiveCounselor.js
lion-front/src/pages/login.js

user 로그인 해야만 들어갈 수 있는 부분과 마이페이지, 공유일기 부분 조금 디자인 다듬고 api 연결했습니다.

FE/ mypage, user 인증, private api 연결

---

lion-back/BackEnd/diary/admin.py
lion-back/BackEnd/diary/models.py
lion-back/BackEnd/diary/serializers.py
lion-back/BackEnd/diary/urls.py
lion-back/BackEnd/diary/views.py

Diary에 user 정보가 저장되도록 업데이트 하였습니다

[BE] Add user info to diary

---

lion-front/src/components/MyPage/PrivateDiary/PrivateDiary.js

diary 작성시 로그인된 유저의 정보가 자동으로 반영되도록 수정하였습니다

[BE] Modify diary to save user info automatically

---

lion-back/BackEnd/accounts/views.py
lion-front/src/api/auth.js

token-cookie

---

lion-back/BackEnd/match/models.py
lion-back/BackEnd/match/serializers.py
lion-back/BackEnd/match/views.py

상담 수락 기능과 오픈 링크 연결 기능 한번에 했고
상담사 리스트를 통해서도 상담 오픈링크 연결되게

client accept and consult with list

---

lion-back/BackEnd/BackEnd/settings.py

accept plus openlink

---

lion-back/BackEnd/diary/admin.py
lion-back/BackEnd/diary/models.py
lion-back/BackEnd/diary/sentiment_analysis.py
lion-back/BackEnd/diary/serializers.py
lion-back/BackEnd/diary/urls.py
lion-back/BackEnd/diary/views.py

diary에서 일기를 작성자만 수정가능하도록 변경하였습니다
공감기능 구현을 위해 diary model에  Reaction 추가하였습니다.

[BE] diary user, reaction update

---

lion-back/BackEnd/accounts/views.py

user comment

---

lion-back/BackEnd/diary/sentiment_analysis.py
lion-back/BackEnd/diary/views.py

Kobert 이용 감정분석을 위한 코드를 일부 추가하였습니다.

[BE]sentiment-analysis-update

---

lion-back/BackEnd/diary/serializers.py

public diary에서 로그인 된 개별 유저가 어떤 공감버튼을 눌렀는지 프론트쪽으로 넘어가도록 수정하였습니다.

[BE] Diary Reaction update

---

lion-back/BackEnd/BackEnd/settings.py
lion-back/BackEnd/accounts/views.py
lion-back/requirements.txt

token-verify

---

lion-back/BackEnd/accounts/views.py

token long

---

lion-back/BackEnd/diary/serializers.py

public diary GET 요청 시 작성자의 username을 반환하도록 수정하였습니다

[BE] publicdiary return username

---

lion-back/BackEnd/match/apps.py
lion-back/BackEnd/match/models.py
lion-back/BackEnd/match/serializers.py
lion-back/BackEnd/match/signals.py
lion-back/BackEnd/match/urls.py
lion-back/BackEnd/match/views.py
lion-front/src/components/matching/Give-counselor/Counselor.js

category error

---

lion-back/BackEnd/match/views.py

permission change

---

lion-back/BackEnd/match/views.py

random matching algorithm change

---

lion-back/BackEnd/diary/sentiment_analysis.py
lion-back/BackEnd/diary/urls.py
lion-back/BackEnd/diary/views.py
lion-front/src/api/axiosConfig.js
lion-front/src/components/MyPage/SentimentResult.js

[BE] sentiment-analysis connect

---

lion-back/BackEnd/accounts/serializers.py
lion-back/BackEnd/accounts/views.py

[BE] user info update
